# Generated by Django 2.2.3 on 2019-07-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=20, null=True)),
                ('sex', models.CharField(max_length=12, null=True)),
                ('place_of_issue', models.CharField(max_length=50, null=True)),
                ('Nid', models.BigIntegerField(default=0)),
                ('fprint_data', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
