# Generated by Django 2.2.3 on 2019-07-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='insurance_dt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=20, null=True)),
                ('sex', models.CharField(max_length=12, null=True)),
                ('nid', models.CharField(max_length=40, null=True)),
                ('policy_no', models.CharField(max_length=30, null=True)),
                ('card_no', models.CharField(max_length=30, null=True)),
                ('valid', models.CharField(max_length=30, null=True)),
                ('patient_contrib', models.CharField(max_length=30, null=True)),
                ('insurance_compny', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
