# Generated by Django 2.2.3 on 2019-07-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nida', '0002_insurance_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('hospitals_name', models.CharField(default='empty', max_length=50)),
                ('speciality', models.CharField(default='empty', max_length=40)),
                ('availability_status', models.CharField(default='empty', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='medical_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiefComplaint', models.TextField()),
                ('pastMedicalHistory', models.TextField()),
                ('familyHistory', models.TextField()),
                ('drugAndAllergyHistory', models.TextField()),
                ('socialHistory', models.TextField()),
                ('nid', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
