# Generated by Django 2.2.3 on 2019-07-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nida', '0003_hospitals_medical_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=30)),
                ('additional_info', models.CharField(max_length=300)),
                ('type_of_injury', models.CharField(max_length=300)),
                ('drug_provided', models.CharField(max_length=300)),
                ('glasgow_coma_scale', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='hospitals',
            name='ho_id',
            field=models.CharField(default='empty', max_length=40),
        ),
    ]
